---
- name: deploy python application
  hosts: prod
  gather_facts: false
  become: yes
  tasks:
    - name: Upload zip file to app server 
      copy:
        src: './myapp-build-{{ buildNumber }}.zip'
        dest: /home/ubuntu/flaskappZIPs/

    - name: Extract zip file
      unarchive:
        src: '/home/ubuntu/flaskappZIPs/myapp-build-{{ buildNumber }}.zip'
        dest: '/home/ubuntu/flaskapp/'
        remote_src: yes

    - name: Ensure venv exists
      command: python3 -m venv venv
      args:
        chdir: /home/ubuntu/flaskapp/
      creates: /home/ubuntu/flaskapp/venv/bin/activate

    - name: Install dependencies
      pip: 
        requirements: requirements.txt
        virtualenv: /home/ubuntu/flaskapp/venv
      args:
        chdir: /home/ubuntu/flaskapp/

    - name: Restart Flask App service
      service:
        name: flaskapp
        state: restarted
