pipeline {
    agent any

    stages {
        stage('Setup') {
            steps {
                sh 'cd 01-jenkins-basics; pip install -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh 'cd 01-jenkins-basics; pytest'
            }
        }
    }
}