pipeline {
    agent any

    stages {
        stage('Setup') {
            steps {
                sh '''
                cd 01-jenkins-basics
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                cd 01-jenkins-basics
                . venv/bin/activate
                pytest
                '''
            }
        }
    }
}