pipeline {
    agent any

    
    stages {

        stage('Setup') {
            steps {
                sh """
                    cd 03-lambda-deployment
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r lambda-app/tests/requirements.txt
                """
            }
        }

        stage('Test') {
            steps {
                sh """
                    cd 03-lambda-deployment
                    . venv/bin/activate
                    pytest
                """
            }
        }

        stage('Build') {
            steps {
                sh """
                    cd 03-lambda-deployment
                    sam build -t lambda-app/template.yaml
                """
            }
        }

        stage('Deploy') {
            steps {
                withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                    sh """
                        cd 03-lambda-deployment
                        sam deploy -t lambda-app/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset
                    """
                }
            }
        }
      
    }
}