pipeline {
    agent any

    stages {
        stage("Setup"){
            steps{
                sh '''
                cd 02-single-server-deployment
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage("Test"){
            steps{
                sh '''
                cd 02-single-server-deployment
                . venv/bin/activate
                pytest
                '''
            }
        }

        stage("Package Code"){
            steps {
                sh " zip -r /home/vagrant/ansible/flaskapp/myapp-build-${env.BUILD_NUMBER}.zip ./02-single-server-deployment/* -x '*.git*' "
            }
        }

        stage("Deploy Code to App server") {
            steps {
                ansiblePlaybook(
                    playbook: '/home/vagrant/ansible/flaskapp/app_deploy.yml',
                    inventory: '/home/vagrant/ansible/flaskapp/hosts.ini',
                    extraVars: [
                        buildNumber: env.BUILD_NUMBER
                    ]
                )
            }
        }
    }

    post {
        always {
            sh "rm -f /home/vagrant/ansible/flaskapp/myapp-build-${env.BUILD_NUMBER}.zip || true"
        }
    }
}