pipeline {
    agent any

    stages {
        stage("Setup"){
            steps{
                sh '''
                cd 02-single-server-deployment
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage("Test"){
            steps{
                sh '''
                cd 02-single-server-deployment
                . venv/bin/activate
                pytest
                '''
            }
        }

        stage("Package Code"){
            steps {
                sh """
                cd 02-single-server-deployment

                zip -r ansible/myapp-build-${env.BUILD_NUMBER}.zip . -x '*.git*' -x '*ansible*' -x '*venv*' -x '__pycache__*' -x '*.pyc'
                """
            }
        }

        stage("Update Server IP") {
            steps {
                sh """
                    cd 02-single-server-deployment

                    sed -i 's/ansible_host=[^ ]*/ansible_host=${env.SERVER_IP}/' ansible/hosts.ini

                    echo 'Updated hosts.ini with new IP: ${env.SERVER_IP}'
                """
            }
        }

        stage("Deploy Code to App server") {
            steps {
                sh 'chmod 400 /tmp/base.pem'
                ansiblePlaybook(
                    playbook: './02-single-server-deployment/ansible/app_deploy.yml',
                    inventory: './02-single-server-deployment/ansible/hosts.ini',
                    extraVars: [
                        buildNumber: env.BUILD_NUMBER
                    ]
                )
            }
        }
    }

    post {
        always {
            sh "rm -f ./02-single-server-deployment/ansible/myapp-build-${env.BUILD_NUMBER}.zip || true"
            echo "Removed packaged zip file: myapp-build-${env.BUILD_NUMBER}.zip"
        }
    }
}