pipeline {
    agent any

    environment {
        IMAGE_NAME = 'rajatrulaniya/flask-app'
        IMAGE_TAG = "${IMAGE_NAME}:${env.GIT_COMMIT}"
        DOCKER_CREDENTIALS = credentials('dockerhub-creds')
    }

    
    stages {

        stage('Setup') {
            steps {
                sh """
                    cd 04-docker
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                """
            }
        }

        stage('Test') {
            steps {
                sh """
                    cd 04-docker
                    . venv/bin/activate
                    pytest
                """
            }
        }    

        stage('Build Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_TAG}
                """
            }
        }

        stage('Docker Push') {
            steps {
                sh """
                    echo $DOCKER_CREDENTIALS_PSW | docker login -u $DOCKER_CREDENTIALS_USR --password-stdin

                    docker push ${IMAGE_TAG}
                """
            }
        }
    }
}